name: FireballWand
main: fr.zyumie.fireballwand.Main
version: 2.9.3
api-version: 1.21
author: Zyumie
commands:
  firewand:
    description: Donne le bâton de feu
    permission: fireballwand.firewand
    usage: /firewand
  kickarmor:
    description: Donne une armure qui kick les joueurs à 3 blocs
    permission: fireballwand.kickarmor
    usage: /kickarmor
  freezewand:
    description: Donne un bâton qui freeze/unfreeze les joueurs
    permission: fireballwand.freezewand
    usage: /freezewand
  unfreezewand-all:
    description: Dégèle tous les joueurs
    permission: fireballwand.unfreezewand
    usage: /unfreezewand-all
  cheatsword:
    description: Donne une Epée Cheat
    permission: fireballwand.cheatsword
    usage: /cheatsword
  cheatmace: 
    description: Donne une Mace Cheat
    permission: fireballwand.cheatmace
    usage: /cheatmace
  diamond_armorcheat:
     description: Donne une Armure en Diamant Cheat
     permission: fireballwand.diamond_armorcheat
     usage: /diamond-armorcheat
  netherite_armorcheat:
     description: Donne une Armures en Netherite Cheat
     permission: fireballwand.netherite_armorcheat
     usage: /netherite-armorcheat